### ISSUE TITLE
Solution for open brackets at the same line as method declaration

### ISSUE THREAD

**Issue by ExE-Boss** [nickgravgaard/ElasticTabstopsDemo#1]
Background
------------
Previously, when the following was used:
```c
void doStuff(`\t`int i,
`\t`int j) {
`\t`// Some comment
}
```
It would look like:
```c
void doStuff( int i,
              int j) {
              // Some comment
}
```
Where the `|` symbol represents a tabstop:
```c
void doStuff(|int i,
             |int j) {
             |// Some comment
}
```
Proposed change
------------------
To fix that, I propose that when multiple consecutive tabs are written, only the last tab is expanded, so that the following:
```c
void doStuff(`\t`int i,
`\t``\t`int j) {
`\t`// Some comment
}
```
Is rendered as:
```c
void doStuff( int i,
              int j) {
    // Some comment
}
```
Where the `|` symbol represents a tabstop:
```c
void doStuff(|int i,
   |         |int j) {
   |// Some comment
}
```

---

### Additional notes:

In order to get this:
```c
void doStuff( int i,   
              int j) { // Leading comment with preceding tab
    // Some comment
}
```
You would do this:
```c
void doStuff(`\t`int i,`\t`
`\t``\t`int j) {`\t`// Leading comment with preceding tab
`\t`// Some comment
}
```
Where the | symbol represents a tabstop:
```c
void doStuff(|int i,  |
   |         |int j) {|// Leading comment with preceding tab
   |// Some comment
}
```

**Comment by ExE-Boss** [comment]
In order to get this:
```c
void doStuff( int i,   
              int j) { // Leading comment
    // Some comment
}
```
You would do this:
```
void doStuff(`\t`int i,`\t`
`\t``\t`int j) {`\t`// Other comment
`\t`// Some comment
}
```
Where the | symbol represents a tabstop:
```c
void doStuff(|int i,  |
   |         |int j) {|// Other comment
   |// Some comment
}
```

**Comment by nickgravgaard** [comment]
Multiple consecutive tabs create empty cells, and if I understand your proposal correctly you're suggesting we should treat these empty cells differently from other cells, and how they should be treated changes according to whether they're the last cell on a line.

I don't know if that can work without causing some big problems.

If we want this:

```C
void doStuff(|int i,
   |         |int j) {
   |// Some comment
}
```
can we still have basic tables with empty cells? We want to still support this case for instance:
```
aaaaaa |bbb |ccc
       |    |ccc
aaa    |bbb |ccc
```

Also, if we could figure out a way to make this work, I suspect we would be making elastic tabstops much less intuitive. I could be wrong though. If you're convinced this is a good idea, the best way to persuade me is to make a usable demo of your idea and let me try it out.

It would be nice if we could find a solution to the case you mention while still having an algorithm that people could understand easily, but if that's not possible the best thing is for people not to write code that way. In that case they should use a code standard where squiggly brackets are always on their own lines, or function parameters aren't aligned.

Do you see the problem?

**Comment by ExE-Boss** [comment]
We can still have basic tables with empty cells, in fact, most things don't change.

The following table would work fine, as all rows have the same amount of columns:
```
aaaaaa|bbb|ccc
      |   |ccc
aaa   |bbb|ccc
```

The only way that table could be broken is if you did any of the following: (i.e. left out the trailing tab on one of the lines that is too long)
```
aaaaaa |bbb
   |   |ccc
aaa|bbb|ccc
```
```
aaa|bbb|ccc
   |   |ccc
aaaaaa |bbb
```
This however wouldn't break:
```
aaaaaa|bbb|ccc
      |   |ccc
aaa   |bbb
```
But this would:
```
aaaaaa |bbb|ccc
   |   |   |ccc
aaa|bbb
```

**Comment by nickgravgaard** [comment]
Could you write some pseudo code describing how you think it should work?

**Comment by ExE-Boss** [comment]
Better, I have an interactive demo (based off the original java demo):
https://github.com/ExE-Boss/ElasticTabstopsDemo/releases/tag/same-line-brackets-b1

The code isn't the prettiest, and there is a fair bit of bugs, but at this point I just want something to work  
(I spent 5 hours trying to squash the largest bugs)

Also when you do this:
```c
`\t`void someWeirdMethod(`\t`int stuff,
`\t`/* some comment */`\t``\t`int other) {
`\t``\t`// Other comment
`\t`}
```
Then this is supposed to happen:
```c
   |void someWeirdMethod(  |int stuff,
   |/* some comment */|    |int other) {
   |                  |// Other comment
   |}
```
Instead of this, which is what currently happens:
```c
                  |void someWeirdMethod( |int stuff,
   |/* some comment */   |   |int other) { // That comment just broke everything
   |                     |// Other comment
   |}
```

**Comment by nickgravgaard** [comment]
Thanks, that's very helpful.

It might be partially because of bugs (adding more than two aligned function parameters broke things for instance) but I'm afraid I think it's just too hard to use and I don't think people will understand it. Sorry, but I don't think this extra complexity is worth it just to fix this one case.
