### ISSUE TITLE
Use vertical tabs to mean insert column here to add support for open brackets at the same line as method declaration

### ISSUE THREAD

**Issue by ExE-Boss** [nickgravgaard/ElasticTabstopsDemo#2]
> *Opening a new issue instead of re-opening #1*

Background
------------
Previously, when the following was used:
```c
void doStuff(`\t`int i,
`\t`int j) {
`\t`// Some comment
}
```
It would look like:
```c
void doStuff( int i,
              int j) {
              // Some comment
}
```
Where the `→|` symbol represents a horizontal tab:
```c
void doStuff(→|int i,
             →|int j) {
             →|// Some comment
}
```

Proposed change
------------------
After think for a long time and searching the internet far and wide, I have came with a solution:
I propose that vertical tabs be used to mean insert column here. The advantage of vertical tabs is that they are considered as whitespace by many modern programming languages and are matched by the `\s` regular expression selector.
```c
void doStuff(`\t`int i,
`\v``\t`int j) {
`\t`// Some comment
}
```
Is rendered as:
```c
void doStuff( int i,
              int j) {
    // Some comment
}
```
Where the `→|` and `↓|` symbols represent a horizontal and vertical tab respectively:
```c
void doStuff(→|int i,
  ↓|         →|int j) {
  →|// Some comment
}
```

---

### Additional notes:

Multiple consecutive vertical tabs in the same column belong to the same column, unless there are non-whitespace characters in front or after them (this is to add support for whitespace dependent languages like Python).

The following:
```ruby (supposed to be python, but that causes issues)
def example(`\t`some,
`\v``\t`args):
`\v`result = some + args;
`\v`return result;
```
Would produce the following:
```python
def example( some,
             args):
    result = some + args;
    return result;
```
Where the `→|` and `↓|` symbols represent a horizontal and vertical tab respectively:
```python
def example(→|some,
  ↓|        →|args):
  ↓|result = some + args;
  ↓|return result;
```

### External resources that led to this idea:

- [https://softwareengineering.stackexchange.com/questions/137290/what-are-the-drawbacks-of-elastic-tabstops#answer-182392](https://softwareengineering.stackexchange.com/questions/137290/what-are-the-drawbacks-of-elastic-tabstops#answer-182392 "coding style - What are the drawbacks of elastic tabstops? - Software Engineering Stack Exchange")
- [http://prog21.dadgum.com/76.html](http://prog21.dadgum.com/76.html "Stop the Vertical Tab Madness")
- [https://en.wikipedia.org/wiki/Tab_key#Tab_characters](https://en.wikipedia.org/wiki/Tab_key#Tab_characters "Tab key - Wikipedia")

**Comment by nickgravgaard** [comment]
Hi again @ExE-Boss :)

I briefly considered using vertical tab characters in the way you suggest when I originally invented the elastic tabstops concept, but I don't think it's a good idea.

Using tabs to jump to the next fixed tabstop, and vertical tabs to jump to a different set of elastic tabstops would be very confusing and hard to use. Users would have to understand there were two kinds of overlapping tabstop, which I think is unlikely given many users don't really understand regular tabstops.

Also, one of the arguments against using tab characters for indenting is that people sometimes have a hard time telling the difference between a tab and a space. Introducing a new whitespace character would make that much worse. The [Stop the Vertical Tab Madness](http://prog21.dadgum.com/76.html) post you referenced is actually against people using vertical tabs for anything. The author writes:

>Here's my simple plea: stop it. Stop mentioning vertical tabs in tutorials and language references. Drop the "\v" sequence in all future programming languages. Retroactively remove it from recent languages, like Python 3. Yes, ASCII character number 11 isn't going away, but there's no reason to draw attention to a relic of computing past.

Finally, and this is a practical implementation issue, this would be very difficult to implement. Implementing elastic tabstops requires a text widget with an API that allows setting tabstops at arbitrary positions on different lines. Sadly, many text widgets do not support this, and this has been the biggest problem getting my invention adopted. The vertical tabs idea would require text widgets to have two sets of tabstop, static and elastic, simultaneously, and I have never seen support for anything like this in any of the many text widgets I have come across.

Thanks again for thinking about this issue, but the simplest solution is often the best, and I think that's what we have with elastic tabstops as they're defined now. The right thing is to change code conventions (placing squiggly {} brackets on their own lines in this case). I mention this in the [Keep it simple, stupid!](http://nickgravgaard.com/elastic-tabstops/#kiss) section on my website:

>Every so often someone will show how they can make code align in a funny way by laying out their code just so, and then go on to come up with a complicated context sensitive and language dependant scheme which fixes that particlar edge case. A better and simpler solution is simply "don't do that, then". Existing code conventions evolved in an environment where displays were character based and tabstops were every N columns. It's not hard to imagine new conventions evolving in a new environment where proportional fonts are possible and text always stays lined up properly.
